# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 03:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20160414_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 15, 3, 16, 30, 576000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 15, 3, 16, 40, 308000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
